FROM oven/bun:1.3.9

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_PEER_HOST
ARG NEXT_PUBLIC_PEER_PORT
ARG NEXT_PUBLIC_PEER_SECURE
ARG NEXT_PUBLIC_RELAY_URL
ARG NEXT_PUBLIC_TURN_URLS
ARG NEXT_PUBLIC_TURN_USERNAME
ARG NEXT_PUBLIC_TURN_CREDENTIAL
ARG NEXT_PUBLIC_ADSENSE_CLIENT_ID
ARG NEXT_PUBLIC_ADSENSE_SLOT_ID

ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_PEER_HOST=${NEXT_PUBLIC_PEER_HOST}
ENV NEXT_PUBLIC_PEER_PORT=${NEXT_PUBLIC_PEER_PORT}
ENV NEXT_PUBLIC_PEER_SECURE=${NEXT_PUBLIC_PEER_SECURE}
ENV NEXT_PUBLIC_RELAY_URL=${NEXT_PUBLIC_RELAY_URL}
ENV NEXT_PUBLIC_TURN_URLS=${NEXT_PUBLIC_TURN_URLS}
ENV NEXT_PUBLIC_TURN_USERNAME=${NEXT_PUBLIC_TURN_USERNAME}
ENV NEXT_PUBLIC_TURN_CREDENTIAL=${NEXT_PUBLIC_TURN_CREDENTIAL}
ENV NEXT_PUBLIC_ADSENSE_CLIENT_ID=${NEXT_PUBLIC_ADSENSE_CLIENT_ID}
ENV NEXT_PUBLIC_ADSENSE_SLOT_ID=${NEXT_PUBLIC_ADSENSE_SLOT_ID}

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start", "--", "-H", "0.0.0.0", "-p", "3000"]
